# Turn on to take no action (for testing and debug purposes). Only logging, getting the bucket and connection tests would be done.
TAKE_NO_ACTION: False
# Connection testing on the s3 bucket
S3_CONNECTION_TEST: False
# Amount of log files to store before removing the oldest one
MAX_LOGFILES: 10
# Turn archive management on or/off. This would also turn off the archive clean up.
ARCHIVE_FILES: True
# Turn cleaning up archive on/off.
CLEAN_UP_ARCHIVE: True
# Archive file prefix
ARCHIVE_FILE_PREFIX: ""
# Archive file suffix
ARCHIVE_FILE_SUFFIX: ""
# Archive file time stamp format
ARCHIVE_FILE_TIMESTAMP_FORMAT: "%Y.%d.%m-%H.%M.%S.%f"
# Use archive container
ARCHIVE_CONTAINER: False
# Archive container dir time stamp format
ARCHIVE_CONTAINER_TIMESTAMP_FORMAT: "%Y.%d.%m-%H.%M.%S.%f"
# Archive container dir prefix
ARCHIVE_CONTAINER_PREFIX: pre_
# Archive container dir suffix
ARCHIVE_CONTAINER_SUFFIX: _suf
# Amount of hours to store transfered files in archive.
ARCHIVE_RETENTION_TIME_HOURS: 1
# Only manage the archive on fully completed uploads
ONLY_ARCHIVE_ON_COMPLETE_UPLOAD: True
